fix nginx verify error
Signed-off-by: ThyeeZz <jialian.ji@zilliz.com>

diff --git a/.github/workflows/master_aws.yml b/.github/workflows/master_aws.yml
--- a/.github/workflows/master_aws.yml
+++ b/.github/workflows/master_aws.yml
@@ -46,18 +46,12 @@ jobs:
           fetch-depth: 1
 
       - name: Verify Nginx configuration
-        uses: addnab/docker-run-action@v3
-        with:
-          image: zilliz/zilliz-web-runner
-          options: -v ${{ github.workspace }}/conf/conf.d/client.conf:/etc/nginx/conf.d/client.conf
-          run: |
-            if nginx -t -c /etc/nginx/nginx.conf; then
-              echo "Nginx configuration is valid."
-            else
-              echo "Nginx configuration is invalid."
-              exit 1
-            fi
         if: always()
+        run: |
+          docker run --rm \
+            -v ${{ github.workspace }}/conf/conf.d/client.conf:/etc/nginx/conf.d/client.conf \
+            zilliz/zilliz-web-runner \
+            sh -c 'if nginx -t -c /etc/nginx/nginx.conf; then echo "Nginx configuration is valid."; else echo "Nginx configuration is invalid."; exit 1; fi'
 
       - name: Setup Node.js
         uses: actions/setup-node@v2
diff --git a/.github/workflows/verify_nginx.yml b/.github/workflows/verify_nginx.yml
--- a/.github/workflows/verify_nginx.yml
+++ b/.github/workflows/verify_nginx.yml
@@ -15,15 +15,9 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Verify Nginx configuration
-        uses: addnab/docker-run-action@v3
-        with:
-          image: zilliz/zilliz-web-runner
-          options: -v ${{ github.workspace }}/conf/conf.d/client.conf:/etc/nginx/conf.d/client.conf
-          run: |
-            if nginx -t -c /etc/nginx/nginx.conf; then
-              echo "Nginx configuration is valid."
-            else
-              echo "Nginx configuration is invalid."
-              exit 1
-            fi
         if: always()
+        run: |
+          docker run --rm \
+            -v ${{ github.workspace }}/conf/conf.d/client.conf:/etc/nginx/conf.d/client.conf \
+            zilliz/zilliz-web-runner \
+            sh -c 'if nginx -t -c /etc/nginx/nginx.conf; then echo "Nginx configuration is valid."; else echo "Nginx configuration is invalid."; exit 1; fi'
