update nginx check
Signed-off-by: ryjiang <jiangruiyi@gmail.com>

diff --git a/.github/workflows/preview_aws.yml b/.github/workflows/preview_aws.yml
--- a/.github/workflows/preview_aws.yml
+++ b/.github/workflows/preview_aws.yml
@@ -10,11 +10,11 @@ on:
   workflow_dispatch:
 
 env:
-  NODE_OPTIONS: '--max_old_space_size=8192'
+  NODE_OPTIONS: "--max_old_space_size=8192"
 
 jobs:
   build:
-    runs-on: 'ubuntu-latest'
+    runs-on: "ubuntu-latest"
     outputs:
       docker-image-tag: ${{ steps.generate-tag-name.outputs.docker_tag }}
     concurrency:
@@ -24,21 +24,25 @@ jobs:
     steps:
       - uses: actions/checkout@v3
         with:
-          ref: 'preview'
+          ref: "preview"
 
       - name: Verify Nginx configuration
-        run: |
-          if sudo nginx -t -c $(pwd)/scripts/test.conf; then
-            echo "Nginx configuration is valid."
-          else
-            echo "Nginx configuration is invalid."
-            exit 1
-          fi
+        uses: addnab/docker-run-action@v3
+        with:
+          image: zilliz/z2:500969b4fa7d576d81da83ad67caef62b42571db-3981
+          options: -v $(pwd)/scripts/test.conf:/etc/nginx/nginx.conf
+          run: |
+            if sudo nginx -t -c $(pwd)/scripts/test.conf; then
+              echo "Nginx configuration is valid."
+            else
+              echo "Nginx configuration is invalid."
+              exit 1
+            fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '18'
+          node-version: "18"
 
       - name: update submodules
         run: |
diff --git a/.github/workflows/verify_nginx.yml b/.github/workflows/verify_nginx.yml
--- a/.github/workflows/verify_nginx.yml
+++ b/.github/workflows/verify_nginx.yml
@@ -28,11 +28,15 @@ jobs:
         if: steps.check-nginx.outputs.installed == 'false'
 
       - name: Verify Nginx configuration
-        run: |
-          if sudo nginx -t -c $(pwd)/scripts/test.conf; then
-            echo "Nginx configuration is valid."
-          else
-            echo "Nginx configuration is invalid."
-            exit 1
-          fi
+        uses: addnab/docker-run-action@v3
+        with:
+          image: zilliz/z2:500969b4fa7d576d81da83ad67caef62b42571db-3981
+          options: -v $(pwd)/scripts/test.conf:/etc/nginx/nginx.conf
+          run: |
+            if sudo nginx -t -c $(pwd)/scripts/test.conf; then
+              echo "Nginx configuration is valid."
+            else
+              echo "Nginx configuration is invalid."
+              exit 1
+            fi
         if: always()
